---

- name: Deploy NGINX Playbook
  hosts: all
  tasks:

    - name: Installing nginx and related dependencies
      become: yes
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          nginx

    - name: Copy nginx.conf to the appropriate location
      become: yes
      copy:
        src: /opt/esp/LMP/nginx.conf
        dest: /etc/nginx/nginx.conf
        remote_src: yes

    - name: Check if nginx is already running
      become: yes
      shell: ps aux | grep [n]ginx | wc -l
      register: st

    - name: Testing if the server is running
      become: yes
      shell: if [ "{{ st.stdout_lines|first }}" == '0' ]; then nginx; else nginx -t; fi
    
    - name: Reload the new NGINX configuration
      become: yes
      shell: nginx -s reload
